services:

  ecommerce:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
      - mongo
      - redis

  postgres:
    image: postgres:14.7
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'

  mongo:
    image: mongo:4.4.27-rc0
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2.3
    env_file:
      - .env
    ports:
      - '6379:6379'

volumes:
  postgres_data:
  mongo_data:
